package com.iridium126.createmanaindustry.mixin.allvr;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import com.iridium126.createmanaindustry.dimension.AllvrDimensions;
import com.iridium126.createmanaindustry.dimension.cube.AllvrCubeMap;
import com.iridium126.createmanaindustry.dimension.cube.AllvrServerLevelDuck;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.FluidState;

/**
 * Routes block data access of the allay dimension to the cube map.
 * <p>
 * This is the single load-bearing piece of the cube architecture on the
 * server: inside the allay dimension, block reads/writes never reach the
 * vanilla column chunk sections (which are empty shells generated by the
 * flat generator with zero layers). Every other dimension is untouched —
 * the guard is a boolean field read plus one reference comparison.
 * <p>
 * Client levels are not intercepted (phase 1 is server-side only; the client
 * sees the empty window columns until ALLVR renders cubes in phase 3).
 */
@Mixin(Level.class)
public abstract class AllvrLevelMixin {

    @Unique
    private AllvrCubeMap allvr$map() {
        Level self = (Level) (Object) this;
        if (self.isClientSide || self.dimension() != AllvrDimensions.ALLAY_LEVEL) {
            return null;
        }
        return self instanceof AllvrServerLevelDuck duck ? duck.allvr$getCubeMap() : null;
    }

    @Inject(method = "getBlockState", at = @At("HEAD"), cancellable = true)
    private void allvr$getBlockState(BlockPos pos, CallbackInfoReturnable<BlockState> cir) {
        AllvrCubeMap map = allvr$map();
        if (map != null) {
            cir.setReturnValue(map.getBlockState(pos));
        }
    }

    /**
     * Targets the 4-arg real implementation — both
     * {@code setBlock(pos, state, flags)} and all recursive neighbour-update
     * paths funnel through it.
     */
    @Inject(method = "setBlock(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;II)Z",
        at = @At("HEAD"), cancellable = true)
    private void allvr$setBlock(BlockPos pos, BlockState state, int flags, int recursionLeft,
                                CallbackInfoReturnable<Boolean> cir) {
        AllvrCubeMap map = allvr$map();
        if (map != null) {
            cir.setReturnValue(map.setBlock(pos, state, flags, recursionLeft));
        }
    }

    @Inject(method = "getFluidState", at = @At("HEAD"), cancellable = true)
    private void allvr$getFluidState(BlockPos pos, CallbackInfoReturnable<FluidState> cir) {
        AllvrCubeMap map = allvr$map();
        if (map != null) {
            cir.setReturnValue(map.getBlockState(pos).getFluidState());
        }
    }

    @Inject(method = "getBlockEntity", at = @At("HEAD"), cancellable = true)
    private void allvr$getBlockEntity(BlockPos pos, CallbackInfoReturnable<BlockEntity> cir) {
        AllvrCubeMap map = allvr$map();
        if (map != null) {
            cir.setReturnValue(map.getBlockEntity(pos));
        }
    }
}
